@startuml
class FitnessCenter {
  name : String
  address : String
}

class Room {
  number : Integer
  maximumCapacity : Integer
}

class Person {
  firstName : String
  familyName : String
  birthDate : Date
}

class Trainer {
  diploma : String
}

class Session {
  date : Date
  startingHour : Time
}

class IndividualSession {
}

class GroupSession {
  type : String
}

Person <|-- Trainer
Session <|-- IndividualSession
Session <|-- GroupSession

FitnessCenter "1" *-- "1..*" Room
Room "1" -- "0..*" Session
Person "1" -- "0..*" IndividualSession
Person "0..*" -- "0..*" GroupSession
Trainer "1" -- "0..*" GroupSession
@enduml
