@startuml
enum BuildingMaterial {
  WOOD
  BRICK
  CONCRETE
}

class House {
  address : String
  buildingMaterial : BuildingMaterial
}

class SemiDetachedHouse {
  hasOwnGarden : Boolean
  numberOfWindows : Integer
}

class Basement {
  name : String
  size : Decimal
}

class EarthBasement {
  humidityLevel : Decimal
}

class ConcreteBasement {
}

class Carport {
  isDoubleCarport : Boolean
  hasFlatRoof : Boolean
}

class Garage {
  hasAutomaticGarageDoor : Boolean
}

class Company {
  name : String
  address : String
}

class JobLog {
  numberOfHours : Decimal
  agreedPrice : Decimal
}

House <|-- SemiDetachedHouse
Basement <|-- EarthBasement
Basement <|-- ConcreteBasement

House "1" *-- "0..1" Basement
SemiDetachedHouse "1" *-- "0,2" Carport
SemiDetachedHouse "1" *-- "0..1" Garage

Company "1..*" -- "0..*" House
House "1" -- "0..*" JobLog
Company "1" -- "0..*" JobLog
@enduml
