@startuml
class Student {
}

class TeachingAssistant {
}

class Course {
}

class Appointment {
}

Student "0..*" -- "0..*" Course
TeachingAssistant "0..*" -- "0..*" Course
Appointment "0..*" -- "1..*" Student
TeachingAssistant "1" -- "0..*" Appointment
Course "1" -- "0..*" Appointment
@enduml
