@startuml
class Person {
  firstName : String
  lastName : String
  emailAddress : String
}

class Organizer {
  postalAddress : String
  phoneNumber : String
  password : String
}

class Attendee {
  password : String
}

class Event {
  startDateTime : DateTime
  endDateTime : DateTime
  occasion : String
}

class EventKind {
  name : String
}

class Location {
  name : String
  address : String
}

class Invitation {
  status : InvitationStatus
}

class Checklist {
}

class Task {
  description : String
}

class EventTask {
  status : TaskStatus
  designatedForAttendees : Boolean
}

enum InvitationStatus {
  WILL_ATTEND
  MAYBE_ATTEND
  CANNOT_ATTEND
  NOT_REPLIED
}

enum TaskStatus {
  NEEDS_TO_BE_DONE
  DONE
  NOT_APPLICABLE
}

Person <|-- Organizer
Person <|-- Attendee

Organizer "1..*" -- "0..*" Event
Event "0..*" -- "1" EventKind
Event "0..*" -- "1" Location
Event "1" *-- "0..*" Invitation
Attendee "1" -- "0..*" Invitation
Event "1" *-- "1" Checklist
Checklist "1" *-- "0..*" EventTask
EventKind "1" *-- "0..*" Task
Task "1" -- "0..*" EventTask
Invitation "0..*" -- "0..*" EventTask
@enduml
