@startuml
class AirlineCompany {
  name : String
}

class Contract {
  deliveryConditions : String
  legalAspects : String
}

class Acquisition {
  negotiatedPrice : Decimal
  chosenOptions : String
  customizations : String
  deliveryDate : Date
}

class Aircraft {
}

class AirplaneModel {
  name : String
}

class Employee {
}

class SalespersonAssignment {
  startDate : Date
  endDate : Date
}

AirlineCompany "1" -- "0..*" Contract
Contract "1" *-- "1..*" Acquisition
Acquisition "1" -- "0..1" Aircraft
AirplaneModel "1" -- "0..*" Acquisition
Contract "1" *-- "1..*" SalespersonAssignment
Employee "1" -- "0..*" SalespersonAssignment
AirlineCompany "0..1" -- "0..*" AirlineCompany
AirlineCompany "0..1" -- "0..*" Aircraft
@enduml
