@startuml
class BusCompany {
    name : String
}

class Bus {
}

class BusLine {
    lineNumber : String
}

class Trajectory {
    operationalStartDate : Date
    cancellationDate : Date
}

class Destination {
    name : String
}

class TownAuthority {
    name : String
}

class ApprovalRequest {
    requestDate : Date
    decisionDate : Date
    decision : ApprovalDecision
}

enum ApprovalDecision {
    APPROVED
    REFUSED
    CHANGE_REQUIRED
}

class Suspension {
    startDate : Date
    endDate : Date
}

class LineCategory {
    name : String
    tripPrice : Decimal
}

class Customer {
    homeAddress : String
    officeAddress : String
    workingHours : String
}

class MENSOCard {
    validFrom : Date
    validUntil : Date
}

class Trip {
    date : Date
    time : Time
    price : Decimal
}

class Invoice {
    invoiceMonth : Integer
    invoiceYear : Integer
    issueDate : Date
    totalAmount : Decimal
    discountPercentage : Decimal
}

class Payment {
    paymentDate : Date
    amount : Decimal
}

BusCompany "1" o-- "0..*" Bus
BusCompany "1" o-- "0..*" BusLine
BusCompany "1" o-- "0..*" Trajectory
BusCompany "1" -- "0..*" ApprovalRequest
BusCompany "1" -- "0..*" Customer
BusLine "1" o-- "1..*" Trajectory
Trajectory "0..*" -- "1..*" Destination
Trajectory "1" -- "0..*" ApprovalRequest
ApprovalRequest "0..*" -- "1..*" TownAuthority
Trajectory "1" *-- "0..*" Suspension
Bus "0..*" -- "0..*" Trajectory
LineCategory "1" -- "0..*" BusLine
Customer "1" -- "0..*" MENSOCard
MENSOCard "1" -- "0..*" Trip
BusLine "1" -- "0..*" Trip
Customer "1" -- "0..*" Invoice
Invoice "0..1" -- "0..*" Trip
Invoice "1" -- "0..1" Payment
@enduml
