@startuml
class Song {
  title : String
  year : Integer
  length : Duration
  genre : String
}

class Single {
}

class Hit {
}

class Artist {
  name : String
  dateOfBirth : Date
  websiteURL : URL
}

class User {
  id : String
  name : String
  address : String
}

class RegularUser {
}

class BusinessUser {
  vatNumber : String
}

class Album {
}

class AlbumTrack {
  trackNumber : Integer
}

class PurchasableItem {
}

class Purchase {
}

class Suggestion {
}

Song <|-- Single
Song <|-- Hit
User <|-- RegularUser
User <|-- BusinessUser
PurchasableItem <|-- Single
PurchasableItem <|-- Album

Artist "1" -- "0..*" Song
BusinessUser "1" -- "0..*" Song
RegularUser "1" -- "0..*" Album
Album "1" *-- "2..*" AlbumTrack
Hit "1" -- "0..*" AlbumTrack
RegularUser "1" -- "0..*" Purchase
PurchasableItem "1" -- "0..*" Purchase
Album "1" -- "0..*" Suggestion
RegularUser "1" -- "0..*" Suggestion
@enduml
