@startuml
class University {
    totalNumberOfEmployees : Integer
}

class Faculty {
    name : String
}

class Institute {
    name : String
    address : String
}

class Employee {
    socialSecurityNumber : String
    name : String
    emailAddress : String
}

class Dean {
}

class ResearchStaff {
}

class AdministrativeStaff {
}

class ResearchAssistant {
    fieldOfResearch : String
}

class Lecturer {
}

class Project {
    name : String
    startDate : Date
    endDate : Date
}

class ProjectParticipation {
    numberOfHours : Number
}

class Course {
    id : Integer
    name : String
    weeklyDurationInHours : Number
}

Employee <|-- Dean
Employee <|-- ResearchStaff
Employee <|-- AdministrativeStaff
ResearchStaff <|-- ResearchAssistant
ResearchAssistant <|-- Lecturer

University "1" *-- "1..*" Faculty
Faculty "1" *-- "1..*" Institute
University "1" -- "0..*" Employee
Faculty "1..*" -- "1" Dean
Institute "1..*" -- "0..*" ResearchAssistant
ResearchAssistant "1" -- "0..*" ProjectParticipation
Project "1" -- "0..*" ProjectParticipation
Lecturer "0..*" -- "1..*" Course
@enduml
