@startuml
class HospitalHouseMD {
}

class Patient {
}

class Doctor {
}

class HeadDoctor {
}

class Nurse {
}

class Illness {
  priorityScore : PriorityScore
}

class Diagnosis {
}

class Treatment {
}

class AppliedTreatment {
  stage : TreatmentStage
}

class ConsentForm {
  status : ConsentStatus
}

enum PriorityScore {
  HIGH
  LOW
}

enum TreatmentStage {
  STAGE_1
  STAGE_2
  STAGE_3
}

enum ConsentStatus {
  SIGNED
  RETRACTED
}

Doctor <|-- HeadDoctor

HospitalHouseMD "1" -- "0..*" Patient
HospitalHouseMD "1" -- "0..*" Doctor
HospitalHouseMD "1" -- "0..*" Nurse
HospitalHouseMD "1" -- "1" HeadDoctor
HospitalHouseMD "1" -- "0..*" Illness
HospitalHouseMD "1" -- "0..*" Treatment

Patient "0..*" -- "1..*" Doctor
Patient "0..*" -- "0..*" Nurse
Patient "1" -- "0..*" Diagnosis
Patient "1" *-- "0..*" ConsentForm

Doctor "1" -- "0..*" Diagnosis
HeadDoctor "0..1" -- "0..*" Diagnosis

Diagnosis "0..*" -- "1" Illness
Diagnosis "1" -- "0..*" AppliedTreatment
Treatment "1" -- "0..*" AppliedTreatment
Illness "0..*" -- "0..*" Treatment
@enduml
